### ISSUE TITLE
API for extensions

### ISSUE THREAD

**Issue by hason** [readthedocs/commonmark.py#106]
I want to to customize parser, renderer etc. It would be awesome expand API to register extensions.

See:
- https://commonmark.thephpleague.com/customization/overview/ and https://github.com/thephpleague/commonmark#community-extensions
- https://github.com/markdown-it/markdown-it#syntax-extensions and https://markdown-it.github.io/markdown-it/#MarkdownIt.use

**Comment by daniele-niero** [comment]
This is actually the only thing that makes me not using CommonMark-py in favor of other tools, which is a shame because I support the idea and arguments behind Commonmark, despite some hate against it, especially from the author of the original Markdown specification

**Comment by mthuurne** [comment]
Since CommonMark doesn't include often-used features like tables yet, extension support is essential for a lot of use cases. I found a project that built such an extension, but they're running into problems, possibly because the parser wasn't designed to be extended: https://github.com/GovReady/CommonMark-py-Extensions/issues/2

The code of CommonMark.py is a lot cleaner than most Markdown processors, so I would rather use this than another library if I could.

**Comment by choldgraf** [comment]
Another +1 for an extension API (or documentation on how to do it). We'd love to build on top of CommonMark-py but need more functionality than commonmark offers

**Comment by chrisjsewell** [comment]
https://github.com/executablebooks/markdown-it-py 😉
